// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function ExportToJSON(arg1:context.Context):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function LoadFile():Promise<string>;

export function OnLoadFile(arg1:context.Context):Promise<void>;

export function OnSaveFile(arg1:context.Context):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;
