// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToJSON(arg1) {
  return window['go']['main']['App']['ExportToJSON'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function OnLoadFile(arg1) {
  return window['go']['main']['App']['OnLoadFile'](arg1);
}

export function OnNewFile(arg1, arg2) {
  return window['go']['main']['App']['OnNewFile'](arg1, arg2);
}

export function OnSaveFile(arg1) {
  return window['go']['main']['App']['OnSaveFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
